blank_issues_enabled: true
contact_links:
    - name: Questions
      url: https://github.com/open-spaced-repetition/py-fsrs/discussions
      about: Please ask general questions here instead of opening an issue.