name: ty typecheck

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python with uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '3.14'

      - name: Install dependencies
        run: uv pip install ty

      - name: Run ty
        run: ty check
      